name: Deploy GitHub Pages from Branch

on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "gh-pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
      - name: Prepare deployment artifact
        run: |
          rm -rf public
          mkdir -p public
          rsync -a --delete --exclude '.git' ./ public/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
